- name: Trigger APIsec scan
  environment: testing
  id: scan
  uses: apisec-inc/apisec-run-scan@v1.0.6
  with:
    apisec-username: ${{ secrets.apisec_username }}
    apisec-password: ${{ secrets.apisec_password }}
    apisec-project: "VAmPI"
    sarif-result-file: "apisec-results.sarif"
    
- name: upload sarif file to repository
  uses: github/codeql-action/upload-sarif@v2
  with:
    sarif_file: ./apisec-results.sarif
